### ISSUE TITLE
关于QWidget 的默认汉化方法

### ISSUE THREAD

**Issue by MarioCrane** [wangwenx190/notes#1]
非常感谢大佬的分享，学到了很多的东西。关于`注：大多数QWidget及其右键菜单（如果有的话）基本都是没有中文翻译的，如果想要完全汉化，则需要自行生成widgets.ts并手动翻译。`这点可以通过自行加载qt提供的qt_zh_CN.qm等翻译文件的方法来解决

**Comment by wangwenx190** [comment]
感谢提醒，我改下 👍
